spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service-spring
    username: root
    password: root

# Keep the connection alive if idle for a long time (needed in production)
spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1

# Show or not log for each sql query
spring:
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        query.substitutions: true 1, false 0
        default_batch_fetch_size: 50
        jdbc.batch_size: 50
        order_inserts: true
        max_fetch_depth: 2
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        connection.zeroDateTimeBehavior: convertToNull